name: offline-cli-validation

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  offline-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run offline CLI validation
        env:
          LOGOS_SEED: "7"
        run: python scripts/offline_cli_validation.py
