name: Phase 6 Portfolio Smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  portfolio-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      LOGOS_OFFLINE_ONLY: "1"
      LIVE_DISABLE_NETWORK: "1"
      MPLBACKEND: Agg
      TZ: UTC
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          if [ -f requirements/dev.txt ]; then python -m pip install -r requirements/dev.txt; fi

      - name: Phase 6 portfolio smoke
        run: make phase6-smoke
