name: Phase 2 Smoke

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          # Fallback dev tools
          pip install pytest ruff black mypy

      - name: Lint
        run: ruff check .

      - name: Format check
        run: black --check .

      - name: Type check
        run: mypy .

      - name: Tests (offline, quick)
        env:
          LOGOS_OFFLINE_ONLY: "1"
        run: pytest -q

      # Optional: run the smoke regression explicitly (if not already covered by tests)
      - name: Smoke regression (seed=7)
        env:
          LOGOS_OFFLINE_ONLY: "1"
        run: |
          python -m logos.live.regression --adapter-mode paper \
            --label regression-smoke --seed 7 \
            --dataset tests/fixtures/live/regression_default \
            --output-dir runs/live/reg_cli