name: Phase 2 Smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    env:
      MPLBACKEND: Agg
      LIVE_DISABLE_NETWORK: "1"
      LOGOS_OFFLINE_ONLY: "1"
      TZ: UTC

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          if [ -f requirements/dev.txt ]; then python -m pip install -r requirements/dev.txt; fi
          # Developer stubs used by mypy
          python -m pip install pandas-stubs types-PyYAML types-peewee

      - name: Lint & Type Check
        run: |
          python -m ruff check .
          python -m black --check .
          python -m mypy .

      - name: Pytest (smoke matrix)
        run: python -m pytest -q

      - name: Smoke regression comparison (seed=7)
        run: |
          python -m logos.live.regression --adapter-mode paper \
            --label regression-smoke --seed 7 \
            --dataset tests/fixtures/live/regression_default \
            --output-dir runs/live/reg_cli